### ISSUE TITLE
remove loading bar

### ISSUE THREAD

**Issue by aster94** [dustincys/brightside#1]
hello, first of all thanks for your good software, do you think to add an option to remove this progress bar in a future release?
![screenshot 2018-04-11 21 51 05](https://user-images.githubusercontent.com/21184718/38639753-86e26ae6-3dd2-11e8-96e2-4c03785eaa55.png)

**Comment by dustincys** [comment]
hi @aster94 ,
First, brightside is not "my" software, it is a quite small and old software (perhaps, it is born in 2003?) hiding in GNU free software project repo, and I do not even know who is the "true" author, I'm sorry. Currently the source code of brightside I pushed here, it has the progress bar removed already, cause it is really annoying and attention diverting, I hate it.

I do not think it is necessary to add an option for removing it in the configuration.

**Comment by aster94** [comment]
my fault!
I am not sure but maybe i have a different version from this one, i installed it with the apt package manager:

`apt show brightside
Package: brightside
Version: 1.4.0-4.1ubuntu3
Priority: optional
Section: universe/gnome
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Ari Pollak <ari@debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 452 kB
Depends: gconf-service, libasound2 (>= 1.0.16), libc6 (>= 2.4), libgconf-2-4 (>= 3.2.5), libgdk-pixbuf2.0-0 (>= 2.22.0), libglade2-0 (>= 1:2.6.4-2~), libglib2.0-0 (>= 2.16.0), libgnome-2-0, libgnomeui-0 (>= 2.22.0), libgtk2.0-0 (>= 2.8.0), libpango-1.0-0 (>= 1.14.0), libwnck22 (>= 1:2.30.7), libx11-6, gconf2 (>= 2.28.1-2)
Download-Size: 83,9 kB
APT-Sources: http://it.archive.ubuntu.com/ubuntu artful/universe amd64 Packages
Description: Add reactivity to the corners and edges of your GNOME desktop
 Brightside provides "edge flipping" to allow you to switch to the adjacent
 workspace simply by pressing your mouse against the edge of the screen.
 .
 Brightside also allows you to assign configurable actions to occur while
 you rest the mouse in a corner of the screen. Currently available actions
 comprise:
 .
    * Fade out volume
    * Prevent screensaver starting
    * Start screensaver and lock screen
    * Enter DPMS standby mode
    * Enter DPMS suspend mode
    * Enter DPMS off mode
    * Dim laptop backlight
    * Custom action
`

maybe them have an older version where there is still this progress bar?

**Comment by dustincys** [comment]
Yes and No, @aster94 .
You have brightside installed through "apt" with 
>  Origin: Ubuntu Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com> .

It is the latest version of "Origin: Ubuntu Maintainer". 
I met the same problem as you mentioned, the progress bar freaks me out (a little OCD?).
Then, I modified  a little source code of brightside, removed the progress bar, and pushed the source code here. 
All you need, first, remove current version of brightside installed by "apt", then  download this source code, compile and install it manually exactly as stated in the README file, finally!  wonderful brightside it is!

**Comment by aster94** [comment]
Thanks Dustin for your help, i think you can close the issue!

**Comment by sujaataarya** [comment]
Greetings! I'm sorry, I did not quite understand which code in which file I need to change in the source code to remove the display of the loadding bar?

**Comment by dustincys** [comment]
hi @sujaataarya , I did change the source code ("remove the loadding bar") and put all the code as initial commit, I do not clearly remember where the modification I made 10 months ago, sorry.
In fact, you do not need to DIY,  just download this source code (bar removed!), compile and install it manually exactly as stated in the README file.

**Comment by sujaataarya** [comment]
@dustincys 
**Thanks**, I recompiled my package as you suggested, here everything turned out and working without that "loading bar"!

I work in Archlinux and collect the file through AUR:
_https://aur.archlinux.org/cgit/aur.git/snapshot/brightside.tar.gz_
Исходники для AUR находятся здесь:
_https://launchpad.net/ubuntu/+archive/primary/+files/brightside_1.4.0.orig.tar.gz_
I replaced the contents of the directory _brightside_1.4.0.orig_ on _brightside-master_ and started the Assembly as usual but with the ''makepkg -e'' key (-e, --noextract — do not extract source files — use the existing '$srcdir/'directory).
