### ISSUE TITLE
Hide icon ffrom tray?

### ISSUE THREAD

**Issue by sujaataarya** [dustincys/brightside#2]
Hey! Please tell me how to remove the display of icons from the system tray?

**Comment by dustincys** [comment]
@sujaataarya 
[https://github.com/dustincys/brightside/blob/master/README#L59](https://github.com/dustincys/brightside/blob/master/README#L59)

**Comment by sujaataarya** [comment]
@dustincys 
**Hello Dustin, thank you for your reply!**
I read this place yesterday:
_''bugfix, tray icon now optional at configure time (use Sessions capture to 
  remove from session)''_
**But it is not quite clear what to do with it.**

I work in Archlinux and collect the file through AUR:
_https://aur.archlinux.org/cgit/aur.git/snapshot/brightside.tar.gz_
Исходники для AUR находятся здесь:
_https://launchpad.net/ubuntu/+archive/primary/+files/brightside_1.4.0.orig.tar.gz_

After reviewing the PKBUILD I found line:
_build() {
  cd " $pkgname - $pkgver.orig"
  LDFLAGS=' - lX11'./configure prefix= / usr --enable-tray-icon
  make
}_
and fixed on  **--disable-tray-icon** but it didn't help.

text appears when you build:
_Summary_
_alsa : yes_
_oss : yes_
_brightness : yes_
_**tray icon : yes**_

**And in the end, the icon is still present in the tray.**

Actually what is the problem — this icon is completely knocked out of the General view of the working environment, although it is transparent, but the background is not transparent and everything looks gray spot. If we can solve this question, I think all who are interested in unity and aesthetics of the design will say thank you.

In addition, I so rarely change the values of the hot corners that I can call the function settings through brightside-poperties in the terminal or something.

**Comment by sujaataarya** [comment]
![_2018-05-14_20-12-50](https://user-images.githubusercontent.com/12985719/40002748-0f7d03f6-57ab-11e8-9dc4-ce0954a75c1f.png)
I mean here is the icon display.

**Comment by dustincys** [comment]
@sujaataarya  why not try "delete the `--enable-tray-icon`" once again ? -_-!__ 
I think there is no option "--disable-tray-icon".
I have tried it on my laptop (Archlinux), it works.

**Comment by dustincys** [comment]
I do not recommend `yaourt` as a right method to install brightside at all.
These following script solve all the problems,

>  git clone https://github.com/dustincys/brightside.git
>  cd brightside
>  ./configure
> make
> sudo make install

then,  no annoying icon in the tray, no annoying progress bar!  brightside it is!

**Comment by dustincys** [comment]
@sujaataarya  I do not like Unity either,  it is an exemplarily anti-aesthetics of the design....
Highly recommend  [fvwm](http://www.fvwm.org/) , here is my configuration https://github.com/dustincys/hifvwm

**Comment by sujaataarya** [comment]
@dustincys 
**OK! Thank you Dustin!**
_From this text:_

git clone https://github.com/dustincys/brightside.git
cd brightside
./configure
make
sudo make install

_I wrote here such an installer for Archlinux_

**PKGBUILD**

# Maintainer: Dustin <https://github.com/dustincys>

pkgname=brightside-git
pkgver=1.4.0
pkgrel=1
pkgdesc="Hotcorner for linux, removed the annoying progress bar"
arch=('i686' 'x86_64')
url="https://github.com/dustincys/brightside"
license=('GPL2')
depends=('alsa-lib' 'gconf' 'libglade' 'libgnomeui' 'libwnck' 'popt')
makedepends=('git' 'intltool' 'rsync')
provides=('brightside')
conflicts=('brightside')
source=("git+https://github.com/dustincys/brightside.git")
sha256sums=('SKIP')

build() {
  cd "brightside"
  ./configure --prefix="/usr"
  make
}

check() {
  cd "brightside"
  make check
}

package() {
  cd "brightside"
  make DESTDIR="$pkgdir" install
}

**.SRCINFO**

pkgbase = brightside-git
	pkgdesc = Hotcorner for linux, removed the annoying progress bar
	pkgver = 1.4.0
	pkgrel = 1
	url = https://github.com/dustincys/brightside
	arch = i686
	arch = x86_64
	license = GPL2
	depends = alsa-lib
	depends = gconf
	depends = libglade
	depends = libgnomeui
	depends = libwnck
	depends = popt
	makedepends = git
	makedepends = intltool
	makedepends = rsync
	provides = brightside
	conflicts = brightside
	source = git+https://github.com/dustincys/brightside.git
	sha256sums = SKIP
pkgname = brightside-git

_Everything was assembled and established safely! (makepkg -si)
It works as it should without any unnecessary elements!_

**Comment by sujaataarya** [comment]
@dustincys 
I think the question is completely solved!
Thank you for your help!
I wish you all the best!

**Comment by sujaataarya** [comment]
[brightside-git.tar.gz](https://github.com/dustincys/brightside/files/2013504/brightside-git.tar.gz)

**Comment by dustincys** [comment]
@sujaataarya  
Wish you a nice day too！ Now I close this issue

**Comment by sujaataarya** [comment]
**@dustincys Hello Dustin!**
How do you look at placing this **brightside-git** package in AUR as it is now. This solution is much better than the existing one (https://launchpad.net/ubuntu/+archive/primary/+files/brightside_1.4.0.orig.tar.gz)?
I tested it with namcap for dependency errors and everything is fine.

**Comment by dustincys** [comment]
helllo, @sujaataarya ,  it is only a slight modification of the original version( a little deletion ), I contribute nothing to brightside yet. So I donot think it's appropriate to use this repo. Thanks.

**Comment by sujaataarya** [comment]
Hello @dustincys!
Wonderful, I agree.
…And still a great improvement!
